In [1]:
import pandas as pd

In [4]:
my_data=pd.read_csv(r"C:\Users\Naman\Desktop\Python\Datasets\DataSets-master\Data_MVLR.csv")

In [9]:
#data split input.... output
y_out=my_data["Petrol_Consumption"]
x_input=my_data.drop("Petrol_Consumption",axis=1)

In [11]:
type(x_input)

pandas.core.frame.DataFrame

In [15]:
#reshap ... convert to nd array
xx_input=x_input.values.reshape(len(x_input),4)
yy_output=y_out.values.reshape(len(y_out),1)

In [17]:
x_train=xx_input[:41]
x_test=xx_input[41:]
y_train=yy_output[:41]
y_test=yy_output[41:]

In [18]:
from sklearn.linear_model import LinearRegression

In [20]:
myobj=LinearRegression()

In [21]:
mylearner=myobj.fit(x_train,y_train)

In [22]:
ya=y_test

In [23]:
yp=mylearner.predict(x_test)

In [24]:
yp

array([[618.11081041],
       [630.64827002],
       [534.91555558],
       [688.39487548],
       [527.69639783],
       [658.98252689],
       [572.85528952]])

In [25]:
ya

array([[699],
       [632],
       [591],
       [782],
       [510],
       [610],
       [524]], dtype=int64)

In [26]:
mylearner.coef_

array([[-2.33964895e+01, -6.67564437e-02,  4.86238217e-04,
         1.39246982e+03]])

In [29]:
mylearner.intercept_

array([240.04962806])

In [30]:
from sklearn.metrics import mean_squared_error

In [31]:
acc=mean_squared_error(ya,yp)

In [32]:
import numpy as np

In [33]:
n=np.sqrt(acc)

In [34]:
n

58.0043867312947