In [2]:
import numpy as np

In [3]:
myarray=np.array([1,2,3,33,44,55,66,100])

In [4]:
type(myarray)

numpy.ndarray

In [5]:
myarray.shape

(8,)

In [6]:
len(myarray)

8

In [7]:
myarray[0]

1

In [8]:
myarray.ndim

1

In [9]:
myarray.mean

<function ndarray.mean>

In [11]:
myarray.mean

<function ndarray.mean>

In [12]:
myarray2d=np.array([[1,11,22],[12,33,44],[13,55,66]])

In [13]:
myarray2d

array([[ 1, 11, 22],
       [12, 33, 44],
       [13, 55, 66]])

In [14]:
myarray2d.ndim

2

In [15]:
myarray2d.shape

(3, 3)

In [16]:
len(myarray2d)

3

In [17]:
myarray2d[0][0]

1

In [18]:
myarray2d[0]

array([ 1, 11, 22])

In [20]:
myarray2d[:,1]

array([11, 33, 55])

In [23]:
myarray2d[1,:]

array([12, 33, 44])

In [24]:
myarray2d.sum()

257

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])